name: external_modules
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  record: ^6.0.0
  dio: ^5.8.0+1
  get: ^4.7.2
  encrypt: ^5.0.3
  in_app_purchase: 3.2.0
  web_socket_channel: ^3.0.0
  shared_preferences: ^2.5.3
  flutter_easyloading: ^3.0.5
  flutter_cache_manager: ^3.3.1
  qcloud_cos_client: ^0.0.7
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  image: 4.0.17
  sqflite: ^2.3.0
  synchronized: ^3.0.0
  path_provider: ^2.1.2
  wakelock_plus: ^1.3.2
  tencent_trtc_cloud: ^2.9.9
  permission_handler: ^12.0.1
  svgaplayer_3: ^3.0.1
  protobuf: ^3.1.0
  http: ^1.0.0
  path_drawing: ^1.0.0
  archive: ^3.1.2
  webview_flutter: ^4.13.0
  intl: ^0.18.1
  dropdown_button2: ^2.0.0
  sign_in_with_apple: ^7.0.1
  video_player: ^2.10.0
  just_audio: ^0.10.4
  audioplayers: ^5.2.1
  adjust_sdk: ^5.4.1
  flutter_image_compress: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
